services:
  # mongo server to store the device messages in
  mongodb:
    container_name: mongodb  # Name of the container
    image: mongo:latest  # Use the official MongoDB image from Docker Hub
    ports:
      - "27017:27017"  # Map the MongoDB port 27017 to the host so we can connect to it via mongo compass
    expose:
      - "27017"
  # rabbitmq image
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    expose:
     - "5672"
     - "15672"
  # device server, intake device messages
  device_svr:
    container_name: device_svr
    build:
      context: ./
      dockerfile: ./services/device_svr/device_svr.Dockerfile
    ports:
      - "9047:9047"
    expose:
     - "5672"
     - "15672"
  # websocket api server, live communication and device messages
  ws_api_svr:
    container_name: ws_api_svr
    build:
      context: ./
      dockerfile: ./services/ws_api_svr/ws_api_svr.Dockerfile
    ports:
      - "9046:9046"
    expose:
     - "5672"
     - "15672"
  # database proxy, http API server
  dbproxy_svr:
    container_name: dbproxy_svr
    build:
      context: ./
      dockerfile: ./services/dbproxy_svr/dbproxy_svr.Dockerfile
    ports:
      - "9045:9045"
    expose:
     - "9044"
     - "5672"
     - "15672"
     - "27017"
  # server for receiving video
  cam_svr:
    container_name: cam_svr
    build:
      context: ./
      dockerfile: ./services/cam_svr/cam_svr.Dockerfile
    ports:
      - "9044:9044"
    expose:
     - "5672"
     - "15672"

# docker run -d -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3